# 🧩 Day 1 Practice — 15 Questions (up to Slicing)

**Topics covered:** array creation · `dtype` / `astype` · attributes · indexing · slicing · boolean indexing
**Level:** Medium · **Rule:** solve using only these topics — no loops!

**Q1.** Create an array of the first 12 **odd numbers** using a single **np.arange** call.

**Q2.** Using **np.linspace**, create 9 equally spaced values from 5 to 45. Before running, **predict the gap** between consecutive values - then verify.

**Q3.** Create **np.arange(1, 10)** and **np.linspace(1, 9, 9)**. Print both and compare their **dtype**. Why are they different?

**Q4.** Create a **6x6 identity matrix** with integer dtype - the output must show no decimal points.

**Q5.** Create a **3x4 matrix** where every element is **5**, and report its shape, size, and ndim.

**Q6.** Given **a = np.array([2, 4, 6])** and **b = np.array([2.0, 4.0, 6.0])** - check both dtypes, then convert b to int with **astype** and verify the dtypes now match.

**Q7.** **Predict the exact output** of **np.array([10.9, 25.5, 39.99]).astype(int)** before running it. What rule does the result prove?

**Q8.** Given **arr = np.arange(10, 101, 10)** - extract: (a) the 4th element, (b) the last element using negative indexing, (c) the 2nd-last element.

**Q9.** From the same arr, slice out exactly **[30 40 50 60]**, and separately produce the **full array in reverse**.

**Q10.** Given **arr = np.arange(1, 21)** - extract **every 3rd element starting from index 1** (result: 2, 5, 8, ...).

**Q11.** Using **one slice only**, extract everything from arr (1-20) EXCEPT the first two and the last two elements.

**Q12.** Using the matrix below, extract: (a) the **3rd row**, (b) the **last column**, (c) the **centre 3x3 block**.
```python
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
```

**Q13.** From the same matrix, extract the **four corner elements** as a 2x2 array - using **step slicing only**.

**Q14.** From the same matrix, extract **every alternate row AND every alternate column** at the same time (the result is 3x3).

**Q15.** Given the marks array below - (a) extract all marks **greater than 60**; (b) extract marks **between 50 and 80** using two conditions with & (remember the parentheses!).
```python
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
```

In [8]:
# Q1
import numpy as np
print(np.arange(1, 24, 2))

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [17]:
# Q2
print(np.linspace(5, 45, 9, dtype=int))

[ 5 10 15 20 25 30 35 40 45]


In [25]:
# Q3
print(np.arange(1, 10).dtype)
print(np.linspace(1, 9, 9).dtype)

int64
float64


In [26]:
# Q4
print(np.eye(6, 6, dtype=int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [34]:
# Q5
m = np.full((3, 4), 5)
print(m.shape)
print(m.size)
print(m.ndim)

(3, 4)
12
2


In [43]:
# Q6
a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])
print('----- Before ------')
print('a type :', a.dtype)
print('b type :', b.dtype)
b = b.astype(int)
print()
print('----- After ------')
print('a type :', a.dtype)
print('b type :', b.dtype)

----- Before ------
a type : int64
b type : float64

----- After ------
a type : int64
b type : int64


In [44]:
# Q7
a = np.array([10.9, 25.5, 39.99]).astype(int)
print(a)

[10 25 39]


In [51]:
# Q8
arr = np.arange(10, 101, 10)
print(arr)
print('4th element :', arr[3])
print('2nd last element :', arr[-2])
print('last element :', arr[-1])


[ 10  20  30  40  50  60  70  80  90 100]
4th element : 40
2nd last element : 90
last element : 100


In [57]:
# Q9
print('sliced :', arr[2 : 6])
print('Reversed :', np.arange(100, 0, -10))

sliced : [30 40 50 60]
Reversed : [100  90  80  70  60  50  40  30  20  10]


In [58]:
# Q10
a = np.arange(1, 21)
print(a[1 : 22 : 3])

[ 2  5  8 11 14 17 20]


In [59]:
# Q11
a = np.arange(1, 21)
print(a[2 : 20])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [67]:
# Q12
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print('3rd Row :', m[2 : 3])
print('last Column :\n', m[0: , 4:5])
print('3x3 matrix :\n', m[1:4 , 1:4])


3rd Row : [[11 12 13 14 15]]
last Column :
 [[ 5]
 [10]
 [15]
 [20]
 [25]]
3x3 matrix :
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [70]:
# Q13
print('4 corners\n', m[0:6:4, 0:6:4])

4 corners
 [[ 1  5]
 [21 25]]


In [73]:
# Q14
print('Alternate 3x3 matrix :\n', m[0:6:2, 0:6:2])

Alternate 3x3 matrix :
 [[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [74]:
# Q15
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
print(marks[marks > 60])

[91 77 62 85 70]


---
✅ **Done?** Cross-check every slicing answer by predicting the output *before* running the cell — that habit is what builds real logic.